#DB H2
spring:
  datasource:
    url: jdbc:h2:mem:currency
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
