#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: postgres

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true